{
 "title": "P&L Settler Bot",
 "tags": [ "Keeper" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Open Positions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open Orders",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "open_orders{instance=\"pnlsettler:9464\"}",
     "legendFormat": "Open Orders"
    }
   ]
  },
  {
   "title": "Open Position Base Asset Value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "open_position_base_asset_amount{instance=\"pnlsettler:9464\"}",
     "legendFormat": "{{marketSymbol}}"
    }
   ]
  },
  {
   "title": "Open Ask Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "open_position_open_asks_amount{instance=\"pnlsettler:9464\"}",
     "legendFormat": "{{marketSymbol}}"
    }
   ]
  },
  {
   "title": "Open Bid Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "open_position_open_bids_amount{instance=\"pnlsettler:9464\"}",
     "legendFormat": "{{marketSymbol}}"
    }
   ]
  },
  {
   "title": "Quote Entry Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "open_position_quote_entry_amount{instance=\"pnlsettler:9464\"}",
     "legendFormat": "{{marketSymbol}}"
    }
   ]
  },
  {
   "title": "Quote Asset Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "open_position_quote_asset_amount{instance=\"pnlsettler:9464\"}",
     "legendFormat": "{{marketSymbol}}"
    }
   ]
  },
  {
   "title": "Open Orders Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "open_position_open_orders_amount{instance=\"pnlsettler:9464\"}",
     "legendFormat": "{{marketSymbol}}"
    }
   ]
  },
  {
   "title": "Last Cumulative Funding Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "open_position_last_cumulative_funding_rate{instance=\"pnlsettler:9464\"}",
     "legendFormat": "{{marketSymbol}}"
    }
   ]
  }
 ]
}