#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED='\033[0;31m';
NC='\033[0m';

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "$BRANCH" = "master" ]]
then
	if [[ $(grep -ciE "drift-labs/sdk.*beta.*" ./package.json) -eq 0 ]]
	then
		echo "$RED$BRANCH should use a beta release of @drift-labs/sdk$NC"
		exit 1
	fi
elif [[ "$BRANCH" = "mainnet-beta" ]]
then
	if [[ $(grep -ciE "drift-labs/sdk.*beta.*" ./package.json) -gt 0 ]]
	then
		echo "$RED$BRANCH should not use a beta release of @drift-labs/sdk$NC"
		exit 1
	fi
else
	echo "skipping drift-labs/sdk package version test for branch $BRANCH"
fi
